//
//  PetBreed.swift
//  Petbulb
//
//  Created by MACPRO on 2017-10-19.
//  Copyright © 2017 Petbulb Corp. All rights reserved.
//

import Foundation


struct PetBreed {
    
    // MARK: Bird Breed List
    private var _birdBreed = ["Abyssinian",
                                "African Grey",
                                "African Ring-Necked Parakeet",
                                "Alexandrine Parakeet",
                                "Amazon",
                                "American Parakeet",
                                "American Singer Canary",
                                "Australian King Parrot",
                                "Australian Parakeet",
                                "Bare-Eyed Cockatoo",
                                "Barraband Parakeet",
                                "Belgian Canary",
                                "Black Lory",
                                "Black-Capped Conure",
                                "Black-Capped Lory",
                                "Black-Cheeked Lovebird",
                                "Black-Headed Caique",
                                "Blossom-Headed Parakeet",
                                "Blue-and-Gold Macaw",
                                "Blue-Crowned Conure",
                                "Blue-Eyed Cockatoo",
                                "Blue-Fronted Amazon",
                                "Blue-Headed Pionus",
                                "Blue-Naped Parrot",
                                "Blue-Streaked Lory",
                                "Blue-Throated Macaw",
                                "Bolborhynchus ",
                                "Border CanaryBourke's Parakeet",
                                "Bronze-Winged Pionus",
                                "Brotogeris",
                                "Brown-Headed Parrot",
                                "Brown-Throated Conure",
                                "Budgerigar",
                                "Buffon's Macaw",
                                "Buggue",
                                "Caique",
                                "Canary",
                                "Canary-Winged Parakeet",
                                "Cape Parrot",
                                "Cardinal Lory",
                                "Chattering Lory",
                                "Cherry-Headed Conure",
                                "Cinnamon Mutation Cockatiel",
                                "Citron-Crested Cockatoo",
                                "Clonclurry Parakeet",
                                "Cockatiel",
                                "Cockatoo",
                                "Collared Aracari",
                                "Congo African Grey",
                                "Conure",
                                "Coral-Billed Pionus",
                                "Crested Canary",
                                "Crimson Rosella",
                                "Crimson-Bellied Conure",
                                "Curl-Crested Aracari",
                                "Derbyan Parakeet",
                                "Diamond Dove",
                                "Dove",
                                "Ducorp's Cockatoo",
                                "Dusky Lory",
                                "Dusky Pionus",
                                "Dusky-Headed Conure",
                                "Duyvenbody's Lory",
                                "Eclectus",
                                "Emerald Toucanet",
                                "English Type Budgie",
                                "Fife Canary",
                                "Finch",
                                "Fischer's Lovebird",
                                "German Roller Canary",
                                "Gloster Canary",
                                "Goffin's Cockatoo",
                                "Gold-Breasted Waxbill",
                                "Gold-Capped Conure",
                                "Golden-Mantled Rosella",
                                "Goldie's Lorikeet",
                                "Gouldian Finch",
                                "Grand Eclectus",
                                "Great-Billed Parrot",
                                "Greater Indian Hill Mynah",
                                "Greater Vasa Parrot",
                                "Green Aracari",
                                "Green-Cheeked Amazon",
                                "Green-Cheeked Conure",
                                "Green-Naped Lorikeet",
                                "Green-Rumped Parrotlet",
                                "Green-Winged Macaw",
                                "Grey-Cheeked Parakeet",
                                "Grey-Headed Parrot",
                                "Guyana Toucanet",
                                "Hahn's Macaw",
                                "Hawk-Headed Parrot",
                                "Hawk-Headed Parrot",
                                "Hyacinth Macaw",
                                "Illiger's Macaw",
                                "Indian Ring-Necked Parakeet",
                                "Ivory-Billed Aracari",
                                "Kakariki",
                                "Keel-Billed Toucan",
                                "Lesser Sulphur-Crested Cockatoo",
                                "Lesser Vasa Parrot",
                                "Lilac-Crowned Amazon",
                                "Lineolated Parakeet",
                                "Lizard Canary",
                                "Lory",
                                "Lovebird",
                                "Lutino Mutation Cockatiel",
                                "Macaw Species",
                                "Major Mitchell's Cockatoo",
                                "Mallee Ringneck Parakeet",
                                "Maroon-Bellied Conure",
                                "Masked Lovebird",
                                "Maximilian's Pionus",
                                "Mealy Amazon",
                                "Meyer's Parrot",
                                "Military Macw",
                                "Mini Macaw",
                                "Mitred Conure",
                                "Moluccan Cockatoo",
                                "Moustached Parakeet",
                                "Muller's Parrot",
                                "Mynah",
                                "Nanday Conure",
                                "Naturalized Quaker",
                                "Niam Niam Parrot",
                                "Noble Macaw",
                                "Normal Green Type Budgie",
                                "Normal grey Cockatiel",
                                "Norwich Canary",
                                "Orange-Chinned Parakeet",
                                "Orange-Fronted Conure",
                                "Orange-Winged Amazon",
                                "Pacific Parrotlet",
                                "Painted Conure",
                                "Parisian-Frilled Canary",
                                "Parrotlet",
                                "Patagonian Conure",
                                "Peach-Faced Lovebird",
                                "Peach-Fronted Conure",
                                "Pearl Mutation Cockatiel",
                                "Pearly Conure",
                                "Pied Mutation Cockatiel",
                                "Pigeon",
                                "Pionus",
                                "Plum-Headed Parakeet",
                                "Poicephalus",
                                "Port Lincoln Parakeet",
                                "Princess of Wales Parakeet",
                                "Psittacula",
                                "Quaker",
                                "Quaker Mutation",
                                "Rainbow Lory",
                                "Rainbow Lorikeet",
                                "Red Lory",
                                "Red-Bellied Macaw",
                                "Red-Bellied Parrot",
                                "Red-Cheeked Cordon Bleu Finch",
                                "Red-Crowned Kakariki",
                                "Red-Fronted Macaw",
                                "Red-Headed Parrot Finch",
                                "Red-Rumped Parakeet",
                                "Red-Sided Eclectus",
                                "Ring-Necked Dove",
                                "Rock Pebbler",
                                "Rock Pigeon",
                                "Rose-Breasted Cockatoo",
                                "Rosella",
                                "Ruppell's Parrot",
                                "Saffron Finch",
                                "Scarlet Macaw",
                                "Scarlet-Chested Parakeet",
                                "Senegal Parrot",
                                "Severe Macaw",
                                "Shaft-Tailed Finch",
                                "Slaty-Headed Parakeet",
                                "Slender-Billed Corella",
                                "Society Finch",
                                "Solomon Islands Eclectus",
                                "Spanish Timbrado Canary",
                                "Spectacled Parrotlet",
                                "Spice Finch",
                                "Stafford Canary",
                                "Star Finch",
                                "Strawberry Finch",
                                "Sulphur-Crested Cockatoo",
                                "Sun Conure",
                                "Swainson's Lorikeet",
                                "Swainson's Toucan",
                                "Tanygnathus",
                                "Timneh African Grey",
                                "Toco Toucan",
                                "Toucan",
                                "Turquoisine Parakeet",
                                "Twenty-Eight Parakeet",
                                "Umbrella Cockatoo",
                                "UnCape Parrot",
                                "Vasa Parrots",
                                "Violet-Necked Lory",
                                "Vosmaeri Eclectus",
                                "Waterslager Canary",
                                "Western Rosella",
                                "White-Bellied Caique",
                                "White-Capped Pionus",
                                "White-Eared Conure",
                                "White-Fronted Amazon",
                                "Yellow-Collared Macaw",
                                "Yellow-Crowned Amazon",
                                "Yellow-Fronted Kakariki",
                                "Yellow-Headed Amazon",
                                "Yellow-Naped Amazon",
                                "Yorkshire Canary",
                                "Zebra Finch"]
    
    
    // MARK: Cat Breed List
    private var _catBreed = ["Abyssinian",
                            "American Shorthair",
                            "Balinese",
                            "Bengal",
                            "Birman",
                            "Bobtail",
                            "Bombay",
                            "British Shorthair",
                            "Burmese",
                            "Burmilla",
                            "Chartreux",
                            "Colorpoint Shorthair",
                            "Cornish Rex",
                            "Coupari",
                            "Curl",
                            "Cymric",
                            "Devon Rex",
                            "Domestic",
                            "Egyptian Mau",
                            "Exotic Shorthair",
                            "German Rex",
                            "Havana Brown",
                            "Himalayan",
                            "Japanese Bobtail",
                            "Javanese",
                            "Kashmir",
                            "Korat",
                            "LaPerm",
                            "Maine Coon",
                            "Manx",
                            "Munchkin",
                            "Nebelung",
                            "Norwegian Forest",
                            "Ocicat",
                            "Oriental Shorthair",
                            "Peke-Faced",
                            "Persian",
                            "Russian Blue",
                            "Savannah",
                            "Scottish Fold",
                            "Selkirk Rex",
                            "Siamese",
                            "Siberian Forest",
                            "Singapura",
                            "Snowshoe",
                            "Sokoke Forest",
                            "Somali",
                            "Spangled",
                            "Sphynx",
                            "Tonkinese",
                            "Turkish Angora",
                            "Turkish Van",
                            "Wirehair",
                            "York Chocolate"]
    
    // MARK: Dog Breed List
    private var dogBreed = ["Affenpinscher",
                            "Afghan Hound",
                            "Airedale Terrier",
                            "Akita",
                            "Alaskan Malamute",
                            "American English Coonhound",
                            "American Eskimo",
                            "American Foxhound",
                            "American Pit Bull Terrier",
                            "American Water Spaniel",
                            "Anatolian Shepherd",
                            "Appenzeller Sennenhunde",
                            "Australian Cattle",
                            "Australian Shepherd",
                            "Australian Terrier",
                            "Azawakh",
                            "Barbet",
                            "Basenji",
                            "Basset Hound",
                            "Beagle",
                            "Bearded Collie",
                            "Bedlington Terrier",
                            "Belgian Malinois",
                            "Belgian Sheepdog",
                            "Belgian Tervuren",
                            "Berger Picard",
                            "Bernese Mountain",
                            "Bichon Frise",
                            "Tan Coonhound",
                            "Russian Terrier",
                            "Bloodhound",
                            "Bluetick Coonhound",
                            "Bolognese",
                            "Border Collie",
                            "Border Terrier",
                            "Borzoi",
                            "Boston Terrier",
                            "Bouvier des Flandres",
                            "Boxer",
                            "Boykin Spaniel",
                            "Bracco Italiano",
                            "Briard",
                            "Brittany",
                            "Brussels Griffon",
                            "Bull Terrier",
                            "Bulldog",
                            "Bullmastiff",
                            "Cairn Terrier",
                            "Canaan",
                            "Cane Corso",
                            "Cardigan Welsh Corgi",
                            "Catahoula Leopard",
                            "Cavalier King",
                            "Cesky Terrier",
                            "Chesapeake Bay Retriever",
                            "Chihuahua",
                            "Chinese Crested",
                            "Chinese Shar-Pei",
                            "Chinook",
                            "Chow Chow",
                            "Clumber Spaniel",
                            "Cockapoo",
                            "Cocker Spaniel",
                            "Collie",
                            "Coton de Tulear",
                            "Curly-Coated Retriever",
                            "Dachshund",
                            "Dalmatian",
                            "Dandie Dinmont Terrier",
                            "Doberman Pinscher",
                            "Dogue de Bordeaux",
                            "English Cocker Spaniel",
                            "English Foxhound",
                            "English Setter",
                            "English Springer Spaniel",
                            "English Toy Spaniel",
                            "Entlebucher Mountain Dog",
                            "Field Spaniel",
                            "Finnish Lapphund",
                            "Finnish Spitz",
                            "Flat-Coated Retriever",
                            "Fox Terrier",
                            "French Bulldog",
                            "German Pinscher",
                            "German Shepherd",
                            "German Shorthaired Pointer",
                            "German Wirehaired Pointer",
                            "Giant Schnauzer",
                            "Glen of Imaal Terrier",
                            "Goldador",
                            "Golden Retriever",
                            "Goldendoodle",
                            "Gordon Setter",
                            "Great Dane",
                            "Great Pyrenees",
                            "Greater Swiss Mountain",
                            "Greyhound",
                            "Harrier",
                            "Havanese",
                            "Ibizan Hound",
                            "Icelandic Sheepdog",
                            "Irish Setter",
                            "Irish Terrier",
                            "Irish Water Spaniel",
                            "Irish Wolfhound",
                            "Italian Greyhound",
                            "Jack Russell Terrier",
                            "Japanese Chin",
                            "Korean Jindo",
                            "Keeshond",
                            "Kerry Blue Terrier",
                            "Komondor",
                            "Kooikerhondje",
                            "Kuvasz",
                            "Labradoodle",
                            "Labrador Retriever",
                            "Lakeland Terrier",
                            "Lancashire Heeler",
                            "Leonberger",
                            "Lhasa Apso",
                            "Lowchen",
                            "Maltese",
                            "Maltese Shih Tzu",
                            "Maltipoo",
                            "Manchester Terrier",
                            "Mastiff",
                            "Miniature Pinscher",
                            "Miniature Schnauzer",
                            "Mutt",
                            "Neapolitan Mastiff",
                            "Newfoundland",
                            "Norfolk Terrier",
                            "Norwegian Buhund",
                            "Norwegian Elkhound",
                            "Norwegian Lundehund",
                            "Norwich Terrier",
                            "Old English Sheepdog",
                            "Otterhound",
                            "Papillon",
                            "Peekapoo",
                            "Pekingese",
                            "Pembroke Welsh",
                            "Pharaoh Hound",
                            "Plott",
                            "Pocket Beagle",
                            "Pointer",
                            "Polish Lowland Sheepdog",
                            "Pomeranian",
                            "Poodle",
                            "Portuguese Water",
                            "Pug",
                            "Puggle",
                            "Puli",
                            "Pyrenean Shepherd",
                            "Rat Terrier",
                            "Redbone Coonhound",
                            "Rhodesian Ridgeback",
                            "Rottweiler",
                            "Saint Bernard",
                            "Saluki",
                            "Samoyed",
                            "Schipperke",
                            "Schnoodle",
                            "Scottish Deerhound",
                            "Scottish Terrier",
                            "Sealyham Terrier",
                            "Shetland Sheepdog",
                            "Shiba Inu",
                            "Shih Tzu",
                            "Siberian Husky",
                            "Silky Terrier",
                            "Skye Terrier",
                            "Sloughi",
                            "Stabyhoun",
                            "Staffordshire Bull Terrier",
                            "Standard Schnauzer",
                            "Sussex Spaniel",
                            "Swedish Vallhund",
                            "Tibetan Mastiff",
                            "Tibetan Spaniel",
                            "Tibetan Terrier",
                            "Toy Fox Terrier",
                            "Vizsla",
                            "Weimaraner",
                            "Welsh Springer Spaniel",
                            "Welsh Terrier",
                            "Whippet",
                            "Xoloitzcuintli",
                            "Yorkipoo",
                            "Yorkshire Terrier"]
    
    
    
    private var fishBreed = ["24-carat G Morly",
                            "Adolfos Cory",
                            "African Catfish",
                            "Albino Catfish",
                            "Albino Festivum",
                            "Albino Shark",
                            "Albino T Barb",
                            "Algae Lemon",
                            "Algae  Siamese",
                            "Angelfish Altum",
                            "Angelfish Gold",
                            "Angelfish Koi",
                            "Angelfish Marble",
                            "Angelfish Silver",
                            "Archer fish",
                            "Axelrods Rainbowfish",
                            "Bala Shark",
                            "Banded Cichlid",
                            "Bandit Cory",
                            "Barb A Tiger",
                            "Barb Gold",
                            "Barb Green Tiger",
                            "Barb Koolaid",
                            "Barb Rosy",
                            "Barb Schwanefeld",
                            "Barb Tiger",
                            "Barb Tinfoil",
                            "Batfish Freshwater",
                            "Betta",
                            "Black Leporinus ",
                            "Black Neon T",
                            "Black Phantom T",
                            "Black Skirt T",
                            "Black Widow T",
                            "Blackfin Cory",
                            "Bleeding Heart T",
                            "Blind Cavefish",
                            "Bloodfin Tetra",
                            "Blood Parrot",
                            "Blue Gourami Morph",
                            "Blue Gourami Hybrid",
                            "Blue Gourami Color",
                            "Boeseman Rainbowfish",
                            "Bolivian Ram",
                            "Brochis Hog-Nosed",
                            "Bronze Cory",
                            "Butterly Ram",
                            "Cardinal Tetra",
                            "Catfish Jordan",
                            "Catfish Pictus",
                            "Catfish Redtail",
                            "Cavefish Blind",
                            "Characin Striped",
                            "Cichlid Banded",
                            "Cichlid Firemouth",
                            "Cichlid Five-bar",
                            "Cichlid Lemon",
                            "Cichlid Midas",
                            "Cichlid Purple",
                            "Cichlid Six-bar",
                            "Cichlid Texas",
                            "Clown Loach",
                            "Common Hatchetfish",
                            "Congo Tetra",
                            "Cory Adolfos",
                            "Cory Bandit",
                            "Cory Blackfin",
                            "Cory Bronze",
                            "Crab Fiddler",
                            "Danio Pearl",
                            "Danio Zebra",
                            "Diamond Tetra",
                            "Dojo Loach",
                            "Emperor Tetra",
                            "Fiddler Crab",
                            "Fighting Fish",
                            "Firemouth Cichlid",
                            "Five-bar Cichlid",
                            "Freshwater Batfish",
                            "Gar",
                            "Giant Whiptail",
                            "Gold Barb",
                            "Golden Whiptail",
                            "Gourami Honey",
                            "Gourami Kissing",
                            "Gourami Leeri",
                            "Gourami Marbeled",
                            "Gourami Moonlight",
                            "Gourami Opaline",
                            "Gourami Pearl",
                            "Gourami Powder Blue",
                            "Gourami Three Spot",
                            "Guppy",
                            "Harlequin",
                            "Hatchetfish Common",
                            "Hog-Nosed Brochis",
                            "Kribensis",
                            "Labidochromis sp Yellow",
                            "Lake Kutubu Rainbowfish",
                            "Lake Wanam Rainbowfish",
                            "Lamprologus Five-stripe",
                            "Lamprologus Six-stripe",
                            "Leleupi",
                            "Livingstoni",
                            "Loach Clown",
                            "Loach Dojo",
                            "Loach Weather",
                            "Madagascar Rainbowfish",
                            "Marbled Gourami",
                            "Marigold Swordtail",
                            "Marigold Wag",
                            "Melanotaenia splendida",
                            "Midas Cichlid",
                            "Millions Fish",
                            "Molly Green",
                            "Molly Red Sunset",
                            "Neon Rainbowfish",
                            "Neon Tetra Black",
                            "Opaline Gourami",
                            "Otocinclus",
                            "Pacu Silver",
                            "Palembang Puffer",
                            "Papuan Rainbowfish",
                            "Parrot Blood",
                            "Pearl Danio",
                            "Pearl Gourami",
                            "Pictus Catfish",
                            "Piranha Red Bellied",
                            "Platy Red Tuxedo",
                            "Platy Red Wagtail",
                            "Pleco Royal",
                            "Rainbowfish Axelrods",
                            "Rainbowfish Boeseman",
                            "Rainbowfish Lake Kutubu",
                            "Rainbowfish Lake Wanam",
                            "Rainbowfish Madagascar",
                            "Rainbowfish Neon",
                            "Rainbowfish Papuan",
                            "Rainbowfish Red",
                            "Ram Bolivian",
                            "Ram Butterfly",
                            "Rasbora Red",
                            "Red Bellied Piranha",
                            "Red Eye Tetra",
                            "Red Fin Shark",
                            "Red Rainbowfish",
                            "Red Ram",
                            "Red Rasbora",
                            "Red Sunset Sailfin Molly",
                            "Red Tailed Shark Albino",
                            "Red Tuxedo Platy",
                            "Red Wagtail Platy",
                            "Redtail Catfish",
                            "Rosy Barb",
                            "Royal Pleco",
                            "Ruby Shark",
                            "Rummy Nose Tetra",
                            "Sailfin Molly",
                            "Schwanefeld's Barb",
                            "Severum",
                            "Shark Albino Red Tailed",
                            "Shark Bala",
                            "Shark Colombian",
                            "Shark Red Fin",
                            "Shark Ruby",
                            "Shark Silver",
                            "Siamese Algae Eater",
                            "Siamese Fighting Fish",
                            "Siamese Tigerfish",
                            "Silver Dollar Myleus rubripinnis",
                            "Silver Dollar Metynnis argenteus",
                            "Silver Pacu",
                            "Silver Shark",
                            "Six-bar Cichlid",
                            "Six-stripe Lamprologus",
                            "Spotted Pimelodus",
                            "Striped Pike Characin",
                            "Swordtail Marigold",
                            "Swordtail Marigold Lyertail",
                            "Swordtail Marigold Wag",
                            "Tetra Black Neon",
                            "Tetra Black Phantom",
                            "Tetra Black Skirt",
                            "Tetra Black Widow",
                            "Tetra Bleeding Heart",
                            "Tetra Bloodfin",
                            "Tetra Cardinal",
                            "Tetra Colombian",
                            "Tetra Congo",
                            "Tetra Diamond",
                            "Tetra Emperor",
                            "Tetra Lemon",
                            "Tetra Red",
                            "Tetra Rummy",
                            "Tetra White",
                            "Tetra Yellow",
                            "Texas Cichlid",
                            "Spot Gourami",
                            "Tiger Barb",
                            "Tigerfish Siamese",
                            "Tinfoil Barb",
                            "Upside Down Catfish",
                            "Weather Loach",
                            "Whiptail Golden",
                            "White Skirt Tetra",
                            "Wimple",
                            "Yellow Tetra",
                            "Zebra Cichlid",
                            "Zebra Danio",
                            "Zebra Danio"]
    
    
    // MARK: Horse Breed List
    private var horseBreed = ["Aegidienberger",
                            "Akhal-Teke",
                            "Altai Horse",
                            "American Cream Draft",
                            "American Indian Horse",
                            "American Paint Horse",
                            "American Quarter Horse",
                            "American Saddlebred",
                            "American Warmblood",
                            "Andalusian Horse",
                            "Anglo-Arabian",
                            "Anglo-Kabarda",
                            "Appaloosa",
                            "Arabian Horse",
                            "Ardennes Horse",
                            "Ariegeois Pony",
                            "Asturcon",
                            "Australian Draught Horse",
                            "Australian Pony",
                            "Australian Riding Pony",
                            "Australian Stock Horse",
                            "Azteca Horse",
                            "Banker Horse",
                            "Barb Horse",
                            "Bardigiano Pony",
                            "Bavarian Warmblood",
                            "Belgian Horse",
                            "Belgian Warmblood",
                            "Black Forest Horse",
                            "Bosnian Pony",
                            "Boulonnais Horse",
                            "Breton Horse",
                            "Brumby",
                            "Budyonny Horse",
                            "Camargue Horse",
                            "Camarillo White Horse",
                            "Campolina",
                            "Chilean Horse",
                            "Chincoteague Pony",
                            "Cleveland Bay",
                            "Clydesdale Horse",
                            "Comtois Horse",
                            "Connemara Pony",
                            "Criollo Horse",
                            "Curly Horse",
                            "Dales Pony",
                            "Dartmoor Pony",
                            "Dole Gudbrandsdal",
                            "Dulmen Pony",
                            "Dutch harness Horse",
                            "Dutch Warmblood",
                            "Eriskay Pony",
                            "Exmoor Pony",
                            "Falabella Horse",
                            "Faroe Pony",
                            "Fell Pony",
                            "Finnhorse",
                            "Fjord Horse",
                            "Frederiksborg Horse",
                            "Freiberger",
                            "Friesian Horse",
                            "Friesian Sport Horse",
                            "Garrano",
                            "Gotland Pony",
                            "Groningen Horse",
                            "Gypsy Vanner Horse",
                            "Hackney Horse",
                            "Hackney Pony",
                            "Haflinger Horse",
                            "Hanoverian Horse",
                            "Heck Horse",
                            "Highland Pony",
                            "Holsteiner Horse",
                            "Hucul Pony",
                            "Icelandic Horse",
                            "Irish Draught",
                            "Irish Sport Horse",
                            "Italian Heavy Draft",
                            "Jutland Horse",
                            "Kentucky Mountain Saddle Horse",
                            "Kerry Bog Pony",
                            "Kiger Mustang",
                            "Kladruber",
                            "Knabstrup",
                            "Konik",
                            "Lipizzan",
                            "Lithuanian Heavy Draught",
                            "Lundy Pony",
                            "Lusitano",
                            "Malapolski Horse",
                            "Mangalarga",
                            "Mangalarga Marchador",
                            "Maremmano",
                            "Marwari Horse",
                            "Miniature Horse",
                            "Misaki",
                            "Miyako Pony",
                            "Mongolian Horse",
                            "Morgan Horse",
                            "Murgese",
                            "Mustang",
                            "National Show Horse",
                            "New Forest Pony",
                            "Newfoundland Pony",
                            "Nokota Horse",
                            "Nonius Horse",
                            "Nordlandshest",
                            "Noriker Horse",
                            "North Swedish Horse",
                            "Oldenburg Horse",
                            "Ostfriesen",
                            "Paso Fino",
                            "Percheron",
                            "Peruvian Paso",
                            "Pindos Pony",
                            "Pony of the Americas",
                            "Pottok",
                            "Przewalski's Horse",
                            "Rocky Mountain Horse",
                            "Russian Trotter",
                            "Selle FranÁais",
                            "Shagya Arabian",
                            "Shetland Pony",
                            "Shire Horse",
                            "Skyros Pony",
                            "Sorraia",
                            "Spanish Jennet Horse",
                            "Spanish Mustang",
                            "Spotted Saddle Horse",
                            "Standardbred Horse",
                            "Suffolk Punch",
                            "Swedish Warmblood",
                            "Tennessee Walking Horse",
                            "Thoroughbred",
                            "Tori Horse",
                            "Trakehner",
                            "Vyatka Horse",
                            "Waler Horse",
                            "Welsh Pony",
                            "Westphalian Horse",
                            "Wielkopolski",
                            "W¸rttemberger",
                            "Yonaguni Horse",
                            "Zemaitukas"]
    
    
    // MARK: Rabbit Breed List
    private var rabbitBreed = ["American Chinchilla",
                                "American Fuzzy Lop",
                                "American Sable",
                                "Belgian Hare",
                                "Beveren",
                                "Blanc de Hotot",
                                "Britannia Petite",
                                "Californian",
                                "Champagne díArgent",
                                "Checkered Giant",
                                "Cinnamon",
                                "Creme díArgent",
                                "Dutch",
                                "Dwarf Hotot",
                                "English Angora",
                                "English Lop",
                                "English Spot",
                                "Flemish Giant",
                                "Florida White",
                                "French Angora",
                                "French Lop",
                                "Giant Angora",
                                "Giant Chinchilla",
                                "Harlequin",
                                "Havana",
                                "Himalayan",
                                "Holland Lop",
                                "Jersey Wooly",
                                "Lilac",
                                "Mini Lop",
                                "Mini Rex",
                                "Mini Satin",
                                "Netherland Dwarf",
                                "New Zealand",
                                "Palomino",
                                "Polish",
                                "Rex",
                                "Rhinelander",
                                "Satin",
                                "Satin Angora",
                                "Silver",
                                "Silver Fox",
                                "Silver Marten",
                                "Standard Chinchilla",
                                "Tan",
                                "Thrianta"]
}
